from pathlib import Path

source_path = Path("sdk/packages/core/src/extensions/tools/executors/reverse-engineering.ts")
source = source_path.read_text()


def replace_once(old: str, new: str) -> None:
    global source
    count = source.count(old)
    if count != 1:
        raise RuntimeError(
            f"reverse-engineering.ts: expected one occurrence, found {count}: {old[:80]!r}"
        )
    source = source.replace(old, new, 1)


replace_once(
    "const GHIDRA_SCRIPT_VERSION = 2;\n",
    "const GHIDRA_SCRIPT_VERSION = 2;\nconst IDA_SCRIPT_VERSION = 1;\n",
)

marker = "async function platformInstallRoots(engine: Engine): Promise<string[]> {"
helper = r'''async function expandGhidraInstallRoots(roots: string[]): Promise<string[]> {
	const expanded = [...roots];
	const executableName =
		process.platform === "win32" ? "analyzeHeadless.bat" : "analyzeHeadless";
	for (const root of roots) {
		try {
			for (const entry of await fs.readdir(root, { withFileTypes: true })) {
				if (!entry.isDirectory()) continue;
				const child = path.join(root, entry.name);
				const hasLauncher = await exists(
					path.join(child, "support", executableName),
				);
				const hasMetadata =
					(await exists(path.join(child, "Ghidra", "application.properties"))) ||
					(await exists(path.join(child, "application.properties")));
				if (hasLauncher || hasMetadata) expanded.push(child);
			}
		} catch {
			// Configured roots can disappear while discovery is running.
		}
	}
	return [...new Set(expanded)];
}

'''
replace_once(marker, helper + marker)

replace_once(
    'const roots = [...(home ? [home] : []), ...discoveredRoots];\n\t\treturn [\n\t\t\t...roots.flatMap((root) => [',
    'const roots = await expandGhidraInstallRoots([\n\t\t\t...(home ? [home] : []),\n\t\t\t...discoveredRoots,\n\t\t]);\n\t\treturn [\n\t\t\t...roots.flatMap((root) => [',
)

insert_point = "function analysisOptionsHash(\n"
ida_helpers = r'''function pythonString(value: string): string {
	return JSON.stringify(value);
}

async function ensureIdaBatchScript(
	outputDir: string,
	operation: "analyze" | "decompile",
	databasePath: string,
) {
	const scriptPath = path.join(outputDir, "ClineIdaBatch.py");
	const outputPath = path.join(outputDir, "decompiled.c");
	const decompileBody =
		operation === "decompile"
			? `
    import ida_funcs
    import ida_hexrays
    import idautils
    if not ida_hexrays.init_hexrays_plugin():
        raise RuntimeError("Hex-Rays decompiler is unavailable")
    with open(OUTPUT_PATH, "w", encoding="utf-8") as writer:
        for ea in idautils.Functions():
            name = ida_funcs.get_func_name(ea)
            writer.write(f"/* {name} @ {ea:#x} */\\n")
            try:
                writer.write(str(ida_hexrays.decompile(ea)))
            except Exception as error:
                writer.write(f"/* decompilation failed: {error} */")
            writer.write("\\n\\n")`
			: "";
	const script = `# Generated by Cline Enhanced for authorized static analysis.
import ida_auto
import ida_loader
import ida_pro

DATABASE_PATH = ${pythonString(databasePath)}
OUTPUT_PATH = ${pythonString(outputPath)}

def main():
    ida_auto.auto_wait()
${decompileBody}
    ida_loader.save_database(DATABASE_PATH, 0)

if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(f"CLINE_IDA_ERROR: {error}")
        ida_pro.qexit(1)
    ida_pro.qexit(0)
`;
	await fs.writeFile(scriptPath, script, { mode: 0o600 });
	return { scriptPath, outputPath };
}

'''
replace_once(insert_point, ida_helpers + insert_point)

replace_once(
    'operation: input.operation,\n\t\t\t\t\tscript_path: input.script_path ?? null,\n\t\t\t\t\tscript_args: input.script_args ?? [],\n\t\t\t\t}',
    'operation: input.operation,\n\t\t\t\t\tscript_path: input.script_path ?? null,\n\t\t\t\t\tscript_args: input.script_args ?? [],\n\t\t\t\t\tidaScriptVersion: IDA_SCRIPT_VERSION,\n\t\t\t\t}',
)
replace_once(
    "\t\tlet reusedAnalysis = false;\n\t\tlet args: string[];",
    "\t\tlet reusedAnalysis = false;\n\t\tlet args: string[];\n\t\tlet expectedOutput: string | undefined;",
)

old_ida = r'''		} else if (engine === "ida") {
			const databaseExists = sameArtifact && (await exists(idaDatabase));
			reusedAnalysis = databaseExists;
			if (gui) {
				args = [databaseExists ? idaDatabase : target];
			} else {
				args = ["-A", `-L${path.join(outputDir, "ida.log")}`];
				if (!databaseExists) args.push(`-o${idaDatabase}`);
				if (input.operation === "decompile") {
					const decompilerOptions = databaseExists
						? "-Ohexrays:-nosave"
						: "-Ohexrays";
					args.push(
						`${decompilerOptions}:${path.join(outputDir, "decompiled.c")}:ALL`,
					);
				}
				if (input.script_path) {
					args.push(
						`-S${[input.script_path, ...(input.script_args ?? [])]
							.map(shellLikeQuote)
							.join(" ")}`,
					);
				}
				args.push(databaseExists ? idaDatabase : target);
			}
'''
new_ida = r'''		} else if (engine === "ida") {
			const databaseExists = sameArtifact && (await exists(idaDatabase));
			reusedAnalysis = databaseExists;
			if (gui) {
				args = [databaseExists ? idaDatabase : target];
			} else {
				args = ["-A", `-L${path.join(outputDir, "ida.log")}`];
				if (!databaseExists) args.push(`-o${idaDatabase}`);
				if (
					input.operation === "analyze" ||
					input.operation === "decompile"
				) {
					const batch = await ensureIdaBatchScript(
						outputDir,
						input.operation,
						idaDatabase,
					);
					args.push(`-S${shellLikeQuote(batch.scriptPath)}`);
					if (input.operation === "decompile") {
						expectedOutput = batch.outputPath;
					}
				} else if (input.script_path) {
					args.push(
						`-S${[input.script_path, ...(input.script_args ?? [])]
							.map(shellLikeQuote)
							.join(" ")}`,
					);
				}
				args.push(databaseExists ? idaDatabase : target);
			}
'''
replace_once(old_ida, new_ida)

old_success = r'''		const succeeded =
			result.exitCode === 0 && !result.timedOut && !result.cancelled;
		if (succeeded) {'''
new_success = r'''		const requiredOutputs = [
			engine === "ida" &&
			(input.operation === "analyze" || input.operation === "decompile")
				? idaDatabase
				: undefined,
			expectedOutput,
		].filter((value): value is string => Boolean(value));
		const outputsExist = (
			await Promise.all(requiredOutputs.map((filePath) => exists(filePath)))
		).every(Boolean);
		const succeeded =
			result.exitCode === 0 &&
			!result.timedOut &&
			!result.cancelled &&
			outputsExist;
		if (succeeded) {'''
replace_once(old_success, new_success)
replace_once(
    "\t\t\tartifactsTruncated: artifacts.length >= 200,\n\t\t\t...result,",
    "\t\t\tartifactsTruncated: artifacts.length >= 200,\n\t\t\tsucceeded,\n\t\t\t...result,",
)
source_path.write_text(source)

test_path = Path("sdk/packages/core/src/extensions/tools/executors/reverse-engineering.test.ts")
tests = test_path.read_text()
start = tests.index('\tit("decompiles every eligible IDA function')
end = tests.index('\n\tit("passes advanced bounded JADX options', start)
replacement = r'''	it("analyzes with a generated IDAPython save-and-exit script", async () => {
		if (process.platform === "win32") return;
		const directory = await fs.mkdtemp(path.join(os.tmpdir(), "cline-re-test-"));
		temporaryDirectories.push(directory);
		const bin = path.join(directory, "bin");
		await executable(
			bin,
			"idat64",
			`for arg in "$@"; do
	case "$arg" in
		-o*) touch "\${arg#-o}" ;;
	esac
done
printf "%s\\n" "$@"`,
		);
		process.env.PATH = `${bin}${path.delimiter}${originalPath ?? ""}`;
		const target = path.join(directory, "sample.bin");
		await fs.writeFile(target, "sample");
		const outputDirectory = path.join(directory, "analysis");
		const result = JSON.parse(
			await createReverseEngineeringExecutor()(
				{ engine: "ida", operation: "analyze", target, output_directory: outputDirectory },
				{} as never,
			),
		);
		expect(result.succeeded).toBe(true);
		expect(result.args.some((arg: string) => arg.startsWith("-S"))).toBe(true);
		const script = await fs.readFile(path.join(outputDirectory, "ClineIdaBatch.py"), "utf8");
		expect(script).toContain("ida_auto.auto_wait()");
		expect(script).toContain("ida_loader.save_database");
		expect(script).toContain("ida_pro.qexit(0)");
		expect(await fs.stat(path.join(outputDirectory, "analysis.i64"))).toBeTruthy();
	});

	it("decompiles IDA functions through a generated IDAPython script", async () => {
		if (process.platform === "win32") return;
		const directory = await fs.mkdtemp(path.join(os.tmpdir(), "cline-re-test-"));
		temporaryDirectories.push(directory);
		const bin = path.join(directory, "bin");
		await executable(
			bin,
			"idat64",
			`for arg in "$@"; do
	case "$arg" in
		-o*) touch "\${arg#-o}" ;;
		-S*)
			script="\${arg#-S}"
			script="\${script#\\\"}"
			script="\${script%\\\"}"
			output=$(sed -n 's/^OUTPUT_PATH = "\\(.*\\)"$/\\1/p' "$script")
			if [ -n "$output" ]; then printf 'pseudocode' > "$output"; fi
			;;
	esac
done
printf "%s\\n" "$@"`,
		);
		process.env.PATH = `${bin}${path.delimiter}${originalPath ?? ""}`;
		const target = path.join(directory, "sample.bin");
		await fs.writeFile(target, "sample");
		const outputDirectory = path.join(directory, "analysis");
		const result = JSON.parse(
			await createReverseEngineeringExecutor()(
				{ engine: "ida", operation: "decompile", target, output_directory: outputDirectory },
				{} as never,
			),
		);
		expect(result.succeeded).toBe(true);
		expect(result.args.some((arg: string) => arg.startsWith("-S"))).toBe(true);
		expect(result.args.some((arg: string) => arg.includes("Ohexrays"))).toBe(false);
		const script = await fs.readFile(path.join(outputDirectory, "ClineIdaBatch.py"), "utf8");
		expect(script).toContain("ida_hexrays.decompile");
		expect(script).toContain("ida_loader.save_database");
		expect(script).toContain("ida_pro.qexit(0)");
		expect(await fs.readFile(path.join(outputDirectory, "decompiled.c"), "utf8")).toBe("pseudocode");
		expect(JSON.parse(await fs.readFile(path.join(outputDirectory, "cline-analysis.json"), "utf8")).sha256).toBe(result.sha256);
	});
'''
tests = tests[:start] + replacement + tests[end:]

insertion = r'''
	it("discovers a Ghidra installation nested one level below the configured root", async () => {
		if (process.platform === "win32") return;
		const directory = await fs.mkdtemp(path.join(os.tmpdir(), "cline-re-test-"));
		temporaryDirectories.push(directory);
		const configuredRoot = path.join(directory, "ghidra-download");
		const installation = path.join(configuredRoot, "ghidra_12.1.3_PUBLIC");
		const launcher = await executable(path.join(installation, "support"), "analyzeHeadless", 'exit 0');
		await fs.mkdir(path.join(installation, "Ghidra"), { recursive: true });
		await fs.writeFile(path.join(installation, "Ghidra", "application.properties"), "application.version=12.1.3\\n");
		process.env.GHIDRA_HOME = configuredRoot;
		const result = JSON.parse(
			await createReverseEngineeringExecutor()(
				{ engine: "ghidra", operation: "discover" },
				{} as never,
			),
		);
		expect(result.capabilities.ghidra.headless).toBe(launcher);
		expect(result.capabilities.ghidra.version).toBe("12.1.3");
	});
'''
anchor = '\tit("analyzes with a generated IDAPython save-and-exit script"'
tests = tests.replace(anchor, insertion + "\n" + anchor, 1)
test_path.write_text(tests)

customizations = Path("CUSTOMIZATIONS.md")
text = customizations.read_text()
old = "- Reverse-engineering and Smali workflows, with cross-platform IDA/Ghidra discovery, executable/version/capability reporting, version-and-option-aware cache reuse, complete output draining, process-tree cancellation, and verified GUI startup."
new = "- Reverse-engineering and Smali workflows, with bounded nested-root Ghidra discovery, generated IDAPython analyze/decompile/save/exit scripts, executable/version/capability reporting, version-and-option-aware cache reuse, complete output draining, process-tree cancellation, and verified GUI startup."
if text.count(old) != 1:
    raise RuntimeError("CUSTOMIZATIONS.md marker mismatch")
customizations.write_text(text.replace(old, new, 1))

verifier = Path("scripts/verify-custom-fork.ts")
text = verifier.read_text()
anchor = '''\t{\n\t\tpath: "sdk/packages/core/src/extensions/tools/executors/supervised-process.ts",\n\t\tmarkers: ['child.once("close"', "process.kill(-child.pid", "exited_early"],\n\t},'''
replacement = anchor + '''\n\t{\n\t\tpath: "sdk/packages/core/src/extensions/tools/executors/reverse-engineering.ts",\n\t\tmarkers: [\n\t\t\t"expandGhidraInstallRoots",\n\t\t\t"ensureIdaBatchScript",\n\t\t\t"ida_hexrays.decompile",\n\t\t\t"ida_loader.save_database",\n\t\t\t"ida_pro.qexit(0)",\n\t\t],\n\t},'''
if text.count(anchor) != 1:
    raise RuntimeError("verify-custom-fork.ts marker mismatch")
verifier.write_text(text.replace(anchor, replacement, 1))
