import {createHash} from "node:crypto";
import {z} from "zod";
import type {AdvancedResult} from "./advanced-analysis";
const Id=z.string().regex(/^[A-Za-z0-9_.:-]{1,80}$/);
const Cfg=z.object({schemaVersion:z.literal(1),entry:Id,blocks:z.array(z.object({id:Id,successors:z.array(Id).max(32)}).strict()).min(1).max(256)}).strict();
const Trace=z.object({schemaVersion:z.literal(1),sinkSeq:z.number().int().nonnegative(),sources:z.array(z.object({seq:z.number().int().nonnegative(),location:Id}).strict()).max(64).default([]),instructions:z.array(z.object({seq:z.number().int().nonnegative(),pc:z.string().max(80).optional(),operation:z.string().min(1).max(80),reads:z.array(Id).max(32),writes:z.array(Id).max(32)}).strict()).min(1).max(10000)}).strict();
const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
function walk(start:string[],links:Map<string,string[]>){const seen=new Set<string>(),pending=[...start];while(pending.length){const n=pending.pop()!;if(seen.has(n))continue;seen.add(n);pending.push(...links.get(n)??[]);}return seen;}
function dominance(nodes:Set<string>,roots:Set<string>,pred:Map<string,string[]>){const sets=new Map<string,Set<string>>();for(const n of nodes)sets.set(n,roots.has(n)?new Set([n]):new Set(nodes));let changed=true,steps=0;while(changed){changed=false;if(++steps>nodes.size+1)throw new Error("Dominance convergence budget exceeded");for(const n of nodes){if(roots.has(n))continue;const ps=(pred.get(n)??[]).filter(x=>nodes.has(x)),next=new Set(ps.length?sets.get(ps[0])!:[]);for(const p of ps.slice(1))for(const x of next)if(!sets.get(p)!.has(x))next.delete(x);next.add(n);const old=sets.get(n)!;if(next.size!==old.size||[...next].some(x=>!old.has(x))){sets.set(n,next);changed=true;}}}return sets;}
export function analyzeProgramCfg(value:unknown){const cfg=Cfg.parse(value),ids=new Set(cfg.blocks.map(b=>b.id));if(ids.size!==cfg.blocks.length||!ids.has(cfg.entry))throw new Error("Invalid CFG IDs or entry");if(cfg.blocks.reduce((n,b)=>n+b.successors.length,0)>2048)throw new Error("CFG edge budget exceeded");const links=new Map<string,string[]>(),pred=new Map<string,string[]>();for(const n of ids)pred.set(n,[]);for(const b of cfg.blocks){if(new Set(b.successors).size!==b.successors.length||b.successors.some(x=>!ids.has(x)))throw new Error("Invalid CFG successor");links.set(b.id,b.successors);for(const dst of b.successors)pred.get(dst)!.push(b.id);}
 const reachable=walk([cfg.entry],links),dom=dominance(reachable,new Set([cfg.entry]),pred),exits=new Set([...reachable].filter(x=>links.get(x)!.length===0)),canExit=new Set([...walk([...exits],pred)].filter(x=>reachable.has(x))),virtual="$exit",postPred=new Map(links);for(const e of exits)postPred.set(e,[virtual]);postPred.set(virtual,[]);const post=dominance(new Set([...canExit,virtual]),new Set([virtual]),postPred);
 const visited=new Set<string>(),order:string[]=[];for(const id of ids){if(visited.has(id))continue;const pending:Array<[string,boolean]>=[[id,false]];while(pending.length){const [n,expanded]=pending.pop()!;if(expanded){order.push(n);continue;}if(visited.has(n))continue;visited.add(n);pending.push([n,true]);for(const dst of links.get(n)!)if(!visited.has(dst))pending.push([dst,false]);}}
 visited.clear();const components:string[][]=[];for(const id of order.reverse()){if(visited.has(id))continue;const component=[...walk([id],new Map([...pred].map(([k,v])=>[k,v.filter(x=>!visited.has(x))])))];for(const n of component)visited.add(n);components.push(component.sort());}
 const loops:Array<{header:string,latch:string,blocks:string[]}>=[];for(const src of reachable)for(const dst of links.get(src)!){if(!dom.get(src)!.has(dst))continue;const body=new Set([dst,src]),pending=src===dst?[]:[src];while(pending.length)for(const p of pred.get(pending.pop()!)!)if(reachable.has(p)&&!body.has(p)){body.add(p);if(p!==dst)pending.push(p);}loops.push({header:dst,latch:src,blocks:[...body].sort()});}
 const cyclic=components.filter(c=>c.length>1||links.get(c[0])!.includes(c[0]));return {reachable:[...reachable].sort(),unreachable:[...ids].filter(x=>!reachable.has(x)).sort(),dominators:Object.fromEntries([...dom].map(([id,v])=>[id,[...v].sort()])),postdominators:Object.fromEntries([...post].filter(([id])=>id!==virtual).map(([id,v])=>[id,[...v].filter(x=>x!==virtual).sort()])),noExitPath:[...reachable].filter(x=>!canExit.has(x)).sort(),stronglyConnectedComponents:components,naturalLoops:loops,irreducibleRegions:cyclic.filter(c=>c.filter(n=>pred.get(n)!.some(p=>reachable.has(p)&&!c.includes(p))).length>1),dispatcherCandidates:cfg.blocks.filter(b=>reachable.has(b.id)&&b.successors.length>=4&&cyclic.some(c=>c.includes(b.id))).map(b=>b.id),equivalence:"not-proven",inputIdentity:hash(cfg)};}
export function analyzeProgramTrace(value:unknown,mode:"slice"|"taint"){const trace=Trace.parse(value),indexes=new Map<number,number>();let previous=-1;trace.instructions.forEach((ins,i)=>{if(ins.seq<=previous||new Set(ins.reads).size!==ins.reads.length||new Set(ins.writes).size!==ins.writes.length)throw new Error("Invalid trace order or duplicate locations");previous=ins.seq;indexes.set(ins.seq,i);});const sink=indexes.get(trace.sinkSeq);if(sink===undefined)throw new Error("Missing trace sink");for(const source of trace.sources)if(!indexes.has(source.seq)||!trace.instructions[indexes.get(source.seq)!].writes.includes(source.location))throw new Error("Source must identify a recorded write");
 const last=new Map<string,number>(),deps:number[][]=[],taints=new Map<string,Set<string>>(),findings:Array<{seq:number,origins:string[]}>=[],unresolved:Array<{seq:number,location:string}>=[];for(let i=0;i<=sink;i++){const ins=trace.instructions[i],origins=new Set<string>(),ds=new Set<number>();for(const name of ins.reads){const def=last.get(name);if(def===undefined){if(unresolved.length<1000)unresolved.push({seq:ins.seq,location:name});}else ds.add(def);for(const origin of taints.get(name)??[])origins.add(origin);}deps[i]=[...ds];for(const name of ins.writes){const next=new Set(origins);for(const src of trace.sources)if(src.seq===ins.seq&&src.location===name)next.add(`${src.seq}:${src.location}`);taints.set(name,next);last.set(name,i);}if(origins.size)findings.push({seq:ins.seq,origins:[...origins].sort()});}
 const kept=new Set<number>(),pending=[sink];while(pending.length){const i=pending.pop()!;if(kept.has(i))continue;kept.add(i);pending.push(...deps[i]);}return {mode,sinkSeq:trace.sinkSeq,slice:mode==="slice"?[...kept].sort((a,b)=>a-b).map(i=>({instruction:trace.instructions[i],dependencies:deps[i].map(p=>trace.instructions[p].seq)})):undefined,influence:mode==="taint"?findings:undefined,unresolvedReads:unresolved,analyzedInstructions:sink+1,totalInstructions:trace.instructions.length,inputIdentity:hash(trace),model:"explicit-location-dependencies",equivalence:"not-proven"};}
export function programEvidenceResult(action:"cfg_analyze"|"trace_slice"|"trace_taint",value:unknown):AdvancedResult{const evidence=action==="cfg_analyze"?analyzeProgramCfg(value):analyzeProgramTrace(value,action==="trace_slice"?"slice":"taint");if(Buffer.byteLength(JSON.stringify(evidence))>1024*1024)throw new Error("Program evidence output budget exceeded");return {protocol:"cline-advanced-analysis/v1",status:"partial",engine:"bounded-program-evidence",engineVersion:"1",evidence,limitations:["Imported CFG/trace is untrusted evidence, not authenticated execution or complete semantics.","No target executes. Explicit register/memory locations are required; aliases, implicit flows and instruction semantics are not inferred.","Dispatcher candidates are structural heuristics, not unflattening or VM recovery. Equivalence is not proved."]};}
