import {createHash,randomUUID} from "node:crypto";
import {constants} from "node:fs";
import {link,open,realpath,rename,rm} from "node:fs/promises";
import {join,isAbsolute} from "node:path";
import {validateNotebook,buildEvidenceGraph,EvidenceGraphSchema} from "@cline/core";
import {z} from "zod";
export const AnalysisDocumentSaveSchema=z.object({kind:z.enum(["notebook","graph-manifest","graph"]),name:z.string().regex(/^[A-Za-z0-9_-]{1,64}$/),document:z.string().min(1).max(1024*1024),confirmWrite:z.literal(true),expectedSha256:z.string().regex(/^[a-f0-9]{64}$/).optional()}).strict();
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
export async function saveAnalysisDocument(workspace:string,value:unknown){const input=AnalysisDocumentSaveSchema.parse(value);if(Buffer.byteLength(input.document)>1024*1024)throw new Error("Document byte budget exceeded");const parsed=JSON.parse(input.document);if(input.kind==="notebook"){const n=validateNotebook(parsed);for(const cell of n.cells)for(const path of [cell.target,cell.compareTarget].filter((x):x is string=>!!x))if(isAbsolute(path)||path.includes("\\")||path.split("/").includes(".."))throw new Error("Notebook inputs must stay relative to this workspace");}else if(input.kind === "graph"){const graph=EvidenceGraphSchema.parse(parsed),ids=new Set(graph.nodes.map(n=>n.id));if(ids.size!==graph.nodes.length||graph.nodes.some(n=>!n.id)||graph.edges.some(e=>!ids.has(e.source)||!ids.has(e.target)))throw new Error("Graph requires unique nodes and valid edge endpoints");}else buildEvidenceGraph(parsed);
 const text=JSON.stringify(parsed,null,2)+"\n";if(Buffer.byteLength(text)>1048576)throw new Error("Serialized document byte budget exceeded");const root=await realpath(workspace),path=join(root,`${input.name}.${input.kind==="notebook"?"analysis-notebook":"analysis-graph"}.json`),lock=await open(`${path}.lock`,"wx",0o600),stage=join(root,`.analysis-${randomUUID()}.tmp`);
 try{if(input.expectedSha256){const old=await open(path,constants.O_RDONLY|(process.platform==="win32"?0:constants.O_NOFOLLOW));try{const info=await old.stat();if(!info.isFile()||info.size>1024*1024)throw new Error("Existing document is unsafe");if(hash(await readBoundedDocument(old))!==input.expectedSha256)throw new Error("Document changed since review");}finally{await old.close();}const file=await open(stage,"wx",0o600);try{await file.writeFile(text);await file.sync();}finally{await file.close();}await rename(stage,path);}else{const file=await open(stage,"wx",0o600);try{await file.writeFile(text);await file.sync();}finally{await file.close();}await link(stage,path);}return {path,sha256:hash(text),kind:input.kind,bytes:Buffer.byteLength(text)};}finally{await lock.close();await rm(`${path}.lock`,{force:true});await rm(stage,{force:true});}}

async function readBoundedDocument(file:Awaited<ReturnType<typeof open>>){const buffer=Buffer.alloc(1048577);let n=0;while(n<buffer.length){const {bytesRead}=await file.read(buffer,n,buffer.length-n,n);if(!bytesRead)break;n+=bytesRead;}if(n>1048576)throw new Error("Existing document grew beyond budget");return buffer.subarray(0,n).toString("utf8");}
