"use client";
import {useState} from "react";import {desktopClient} from "@/lib/desktop-client";
const notebook={schemaVersion:1,title:"Static investigation",cells:[{id:"triage",action:"triage",target:"sample.bin",dependsOn:[]}]};
const graph={schemaVersion:1,nodes:[],edges:[],coverage:["Manually authored: untrusted evidence"],sourceHashes:[]};
export function AnalysisAuthoring({kind,common,onPrepare}:{kind:"notebook"|"graph",common:Record<string,unknown>,onPrepare:(r:Record<string,unknown>)=>Promise<void>}){
const [name,setName]=useState(kind==="notebook"?"investigation":"evidence"),[text,setText]=useState(JSON.stringify(kind==="notebook"?notebook:graph,null,2)),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState<{path:string,sha256:string}|null>(null),[expectedHash,setExpectedHash]=useState<string|undefined>(),[query,setQuery]=useState('{"limit":100}');
const button="min-h-11 rounded-md border border-border px-3 py-2 text-sm disabled:opacity-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary";
function change(value:string){setReviewed(false);setSaved(null);setError("");if(new TextEncoder().encode(value).length>1048576){setError("Document exceeds its 1 MiB byte budget");return;}setText(value);}
async function save(){setBusy(true);setError("");try{JSON.parse(text);const result=await desktopClient.invoke<{path:string,sha256:string}>("save_analysis_document",{...common,kind,name,document:text,confirmWrite:true,...(expectedHash?{expectedSha256:expectedHash}:{})});setSaved(result);setExpectedHash(result.sha256);setReviewed(false);}catch(e){setError(e instanceof Error?e.message:"Document save failed");}finally{setBusy(false);}}
async function prepare(action:string){if(!saved)return;try{await onPrepare({operation:"advanced_analysis",engine:"auto",advanced_action:action,target:saved.path,report_format:"json",timeout_ms:120000,...(action==="graph_query"?{advanced_options:{graph_query:JSON.parse(query)}}:{})});}catch(e){setError(e instanceof Error?e.message:"Preparation failed");}}
function addCell(){try{const doc=JSON.parse(text);if(!Array.isArray(doc.cells)||doc.cells.length>=20)throw new Error("Up to 20 static cells supported");doc.cells.push({id:`cell_${doc.cells.length+1}`,action:"triage",target:"sample.bin",dependsOn:[]});change(JSON.stringify(doc,null,2));}catch(e){setError(e instanceof Error?e.message:"Invalid notebook");}}
return <section aria-label="Analysis document authoring" className="space-y-4"><h3 className="text-base font-semibold">{kind==="notebook"?"Static notebook editor":"Evidence graph editor"}</h3><p className="text-sm text-muted-foreground">{kind==="notebook"?"Data-only DAGs with workspace-relative inputs. Scripts, runtime cells and keys are rejected.":"Paste graph_build evidence.graph JSON. Candidate links are not confirmed JNI bindings; imported or edited reports are not authenticated facts."}</p>
<label className="block text-sm">Document name<input aria-label="Analysis document name" className="mt-2 min-h-11 w-full rounded-md border border-input bg-background px-3" value={name} onChange={e=>{setName(e.target.value);setExpectedHash(undefined);setSaved(null);setReviewed(false);}}/></label><label className="block text-sm">Document JSON<textarea aria-label="Analysis document JSON" maxLength={1048576} className="mt-2 min-h-64 w-full rounded-md border border-input bg-background p-3 font-mono text-sm" value={text} onChange={e=>change(e.target.value)} spellCheck={false}/></label>
{kind==="notebook"&&<button className={button} type="button" onClick={addCell}>Add static cell</button>}{expectedHash&&<p className="break-all text-sm text-muted-foreground">Update must match saved SHA-256: {expectedHash}</p>}
<label className="flex min-h-11 items-start gap-3 text-sm"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>{expectedHash?"I approve updating this document only if its saved hash is unchanged.":"I approve saving a new workspace file, without overwriting existing files."}</label><button className={button} type="button" disabled={!reviewed||busy||!name} onClick={()=>void save()}>{busy?"Validating and saving…":"Validate and save document"}</button>{error&&<p role="alert" className="break-words text-sm text-destructive">{error}</p>}
{saved&&<div className="space-y-3 rounded-lg border border-border p-3"><p className="break-all text-sm">Saved: {saved.path}</p><p className="break-all font-mono text-sm">SHA-256: {saved.sha256}</p>{kind==="notebook"?<><button className={button} type="button" onClick={()=>void prepare("notebook_validate")}>Prepare notebook preflight</button><button className={button} type="button" onClick={()=>void prepare("notebook_run")}>Prepare static notebook run</button></>:<><label className="block text-sm">Graph query JSON<textarea aria-label="Graph query JSON" className="mt-2 min-h-20 w-full rounded-md border border-input bg-background p-3 font-mono text-sm" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className={button} type="button" onClick={()=>void prepare("graph_query")}>Prepare graph query</button></>}<p className="text-sm text-muted-foreground">Saving never executes analysis. Each run requires separate exact-request approval.</p></div>}</section>;
}
