"""Materialize reviewed V4 source after local workspace loss.
Runs only on the dedicated branch; generated source is committed before building.
Never builds an installer from uncommitted generated changes.
"""
from pathlib import Path
import hashlib,json,subprocess
r=Path.cwd()
BASE='28463aae8554504337a026ff610c016d84a84d15'
marker=r/'docs/V4_SOURCE_RECOVERY.json'
identity=hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
previous=json.loads(marker.read_text()) if marker.exists() else None
if previous and previous['generatorSha256']==identity:
 print('Source recovery already applied.');raise SystemExit(0)
if subprocess.check_output(['git','branch','--show-current'],text=True).strip()!='feat/advanced-analysis-v4-20261005':raise RuntimeError('Dedicated V4 branch required')
changed=[]
def put(name,text):
 p=r/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text);changed.append(name)
def base(name):
 value=subprocess.check_output(['git','show',BASE+':'+name],text=True)
 current=(r/name).read_text()
 approved=previous and previous.get('hashes',{}).get(name)==hashlib.sha256(current.encode()).hexdigest()
 if current!=value and not approved:raise RuntimeError('Refusing to overwrite unexpected changes: '+name)
 return value
AUTHOR='apps/examples/desktop-app/webview/components/views/chat/analysis-authoring.tsx'
put(AUTHOR,'''"use client";
import {useState} from "react";import {desktopClient} from "@/lib/desktop-client";
const notebook={schemaVersion:1,title:"Static investigation",cells:[{id:"triage",action:"triage",target:"sample.bin",dependsOn:[]}]};
const graph={schemaVersion:1,nodes:[],edges:[],coverage:["Manually authored: untrusted evidence"],sourceHashes:[]};
export function AnalysisAuthoring({kind,common,onPrepare}:{kind:"notebook"|"graph",common:Record<string,unknown>,onPrepare:(r:Record<string,unknown>)=>Promise<void>}){
const [name,setName]=useState(kind==="notebook"?"investigation":"evidence"),[text,setText]=useState(JSON.stringify(kind==="notebook"?notebook:graph,null,2)),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState<{path:string,sha256:string}|null>(null),[expectedHash,setExpectedHash]=useState<string|undefined>(),[query,setQuery]=useState('{"limit":100}');
const button="min-h-11 rounded-md border border-border px-3 py-2 text-sm disabled:opacity-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary";
function change(value:string){setReviewed(false);setSaved(null);setError("");if(new TextEncoder().encode(value).length>1048576){setError("Document exceeds its 1 MiB byte budget");return;}setText(value);}
async function save(){setBusy(true);setError("");try{JSON.parse(text);const result=await desktopClient.invoke<{path:string,sha256:string}>("save_analysis_document",{...common,kind,name,document:text,confirmWrite:true,...(expectedHash?{expectedSha256:expectedHash}:{})});setSaved(result);setExpectedHash(result.sha256);setReviewed(false);}catch(e){setError(e instanceof Error?e.message:"Document save failed");}finally{setBusy(false);}}
async function prepare(action:string){if(!saved)return;try{await onPrepare({operation:"advanced_analysis",engine:"auto",advanced_action:action,target:saved.path,report_format:"json",timeout_ms:120000,...(action==="graph_query"?{advanced_options:{graph_query:JSON.parse(query)}}:{})});}catch(e){setError(e instanceof Error?e.message:"Preparation failed");}}
function addCell(){try{const doc=JSON.parse(text);if(!Array.isArray(doc.cells)||doc.cells.length>=20)throw new Error("Up to 20 static cells supported");doc.cells.push({id:`cell_${doc.cells.length+1}`,action:"triage",target:"sample.bin",dependsOn:[]});change(JSON.stringify(doc,null,2));}catch(e){setError(e instanceof Error?e.message:"Invalid notebook");}}
return <section aria-label="Analysis document authoring" className="space-y-4"><h3 className="text-base font-semibold">{kind==="notebook"?"Static notebook editor":"Evidence graph editor"}</h3><p className="text-sm text-muted-foreground">{kind==="notebook"?"Data-only DAGs with workspace-relative inputs. Scripts, runtime cells and keys are rejected.":"Paste graph_build evidence.graph JSON. Candidate links are not confirmed JNI bindings; imported or edited reports are not authenticated facts."}</p>
<label className="block text-sm">Document name<input aria-label="Analysis document name" className="mt-2 min-h-11 w-full rounded-md border border-input bg-background px-3" value={name} onChange={e=>{setName(e.target.value);setExpectedHash(undefined);setSaved(null);setReviewed(false);}}/></label><label className="block text-sm">Document JSON<textarea aria-label="Analysis document JSON" maxLength={1048576} className="mt-2 min-h-64 w-full rounded-md border border-input bg-background p-3 font-mono text-sm" value={text} onChange={e=>change(e.target.value)} spellCheck={false}/></label>
{kind==="notebook"&&<button className={button} type="button" onClick={addCell}>Add static cell</button>}{expectedHash&&<p className="break-all text-sm text-muted-foreground">Update must match saved SHA-256: {expectedHash}</p>}
<label className="flex min-h-11 items-start gap-3 text-sm"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>{expectedHash?"I approve updating this document only if its saved hash is unchanged.":"I approve saving a new workspace file, without overwriting existing files."}</label><button className={button} type="button" disabled={!reviewed||busy||!name} onClick={()=>void save()}>{busy?"Validating and saving…":"Validate and save document"}</button>{error&&<p role="alert" className="break-words text-sm text-destructive">{error}</p>}
{saved&&<div className="space-y-3 rounded-lg border border-border p-3"><p className="break-all text-sm">Saved: {saved.path}</p><p className="break-all font-mono text-sm">SHA-256: {saved.sha256}</p>{kind==="notebook"?<><button className={button} type="button" onClick={()=>void prepare("notebook_validate")}>Prepare notebook preflight</button><button className={button} type="button" onClick={()=>void prepare("notebook_run")}>Prepare static notebook run</button></>:<><label className="block text-sm">Graph query JSON<textarea aria-label="Graph query JSON" className="mt-2 min-h-20 w-full rounded-md border border-input bg-background p-3 font-mono text-sm" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className={button} type="button" onClick={()=>void prepare("graph_query")}>Prepare graph query</button></>}<p className="text-sm text-muted-foreground">Saving never executes analysis. Each run requires separate exact-request approval.</p></div>}</section>;
}
''')
path='apps/examples/desktop-app/webview/components/views/chat/analysis-workbench.tsx'
v=base(path)
v=v.replace('"use client";','"use client";\nimport {AnalysisAuthoring} from "./analysis-authoring";',1).replace('| "analyze"','| "notebook" | "graph" | "runtime" | "analyze"',1).replace('{ id: "analyze", icon: Binary, label: "Analyze" },','{ id: "analyze", icon: Binary, label: "Analyze" },\n {id:"notebook",icon:ListChecks,label:"Notebook"}, {id:"graph",icon:Activity,label:"Graph"}, {id:"runtime",icon:ShieldAlert,label:"Isolated runtime"},',1)
v=v.replace('const [advancedAction,setAdvancedAction]=useState("suite");','const [advancedAction,setAdvancedAction]=useState("suite");\n const [advancedOptions,setAdvancedOptions]=useState("{}");const [runtimeSymbol,setRuntimeSymbol]=useState("main");const [architecture,setArchitecture]=useState("x86_64");const [uploadConfirmed,setUploadConfirmed]=useState(false);const [runtimeConfirmed,setRuntimeConfirmed]=useState(false);').replace('setPendingPlan(plan);','setPendingPlan(plan);setUploadConfirmed(false);setRuntimeConfirmed(false);',1).replace('if (!pendingPlan) return;','if (!pendingPlan) return;\n if(pendingPlan.kind === "dynamic"&&(!uploadConfirmed||!runtimeConfirmed))return;',1)
v=v.replace('} else {\n\t\t\t\tresponse = await desktopClient.invoke(','} else if(pendingPlan.kind === "dynamic"){response=await desktopClient.invoke("run_dynamic_analysis",{...common,planId:pendingPlan.id,executionToken:approved.executionToken,confirmExecution:runtimeConfirmed,confirmArtifactUpload:uploadConfirmed,input:pendingPlan.request});} else {\n\t\t\t\tresponse = await desktopClient.invoke(',1)
v=v.replace('const prepareStatic = (kind: "static" | "gui") => {','const prepareStatic = (kind: "static" | "gui") => {\n if(kind === "static"&&operation === "advanced_analysis")try{JSON.parse(advancedOptions);}catch{toast({variant:"destructive",title:"Invalid advanced options JSON"});return;}').replace('advanced_action:advancedAction} : {}','advanced_action:advancedAction,advanced_options:JSON.parse(advancedOptions)} : {}',1)
v=v.replace('<option value="triage">Blob triage</option>','<option value="triage">Blob triage</option>'+''.join('<option value="'+a+'">'+label+'</option>' for a,label in [('cfg_analyze','CFG dominance and loops'),('trace_slice','Imported trace slice'),('trace_taint','Imported trace influence'),('lift_native_ir','Miasm bounded IR'),('deobfuscation_pass','Miasm expression pass'),('native_disassemble','Native range disassembly'),('decrypt_blob','Known-key authenticated decryption'),('graph_build','Build graph from result manifest')]))
v=v.replace('</select><p className="mt-2 text-xs font-normal','</select><span className="mt-3 block">Advanced options JSON</span><textarea aria-label="Advanced options JSON" className="mt-2 min-h-24 w-full rounded-md border border-input bg-background p-3 font-mono text-sm" value={advancedOptions} onChange={e=>setAdvancedOptions(e.target.value)}/><p className="mt-2 text-xs font-normal',1)
a=v.index('\t\t\t\t\t{mode === "analyze" && (')
v=v[:a]+'''{(mode==="notebook"||mode==="graph")&&<AnalysisAuthoring key={mode} kind={mode} common={common} onPrepare={request=>prepare("static",request)}/>}
{mode==="runtime"&&<section className="space-y-4"><h3 className="text-base font-semibold">Isolated QBDI submission</h3><p className="text-sm text-muted-foreground">Requires an operator-provisioned disposable VM and compatible signed worker. The desktop does not execute a native sample. Signed operator claims are not hardware attestation.</p><label className="block text-sm">Artifact path<Input aria-label="Runtime artifact path" value={target} onChange={e=>setTarget(e.target.value)}/></label><label className="block text-sm">Exported function symbol<Input aria-label="Runtime symbol" value={runtimeSymbol} onChange={e=>setRuntimeSymbol(e.target.value)}/></label><label className="block text-sm">Architecture<select className="min-h-11 w-full rounded-md border border-input bg-background px-3" value={architecture} onChange={e=>setArchitecture(e.target.value)}><option value="x86_64">x86-64</option><option value="arm64">ARM64</option></select></label><p className="text-sm text-muted-foreground">Worker endpoint, key fingerprint and artifact identity are bound to approval. Upload and authorized execution require separate acknowledgments. Worker egress stays disabled.</p>{formButton("Prepare isolated-runtime task",()=>void prepare("dynamic",{operation:"trace_native_region",target:target.trim(),symbol:runtimeSymbol,architecture,instruction_limit:10000,timeout_ms:60000}),!target.trim())}</section>}
'''+v[a:]
a=v.index('\t\t\t\t\t\t\t\t\t{formButton(',v.index('{mode === "approvals"'))
v=v[:a]+'''{pendingPlan.kind === "dynamic"&&<div className="space-y-3 text-sm"><label className="flex min-h-11 items-start gap-3"><input type="checkbox" checked={uploadConfirmed} onChange={e=>setUploadConfirmed(e.target.checked)}/>I approve uploading this exact artifact to the reviewed worker.</label><label className="flex min-h-11 items-start gap-3"><input type="checkbox" checked={runtimeConfirmed} onChange={e=>setRuntimeConfirmed(e.target.checked)}/>I am authorized to execute this exact artifact in that isolated worker with egress disabled.</label></div>}
'''+v[a:]
v=v.replace('() => void approveAndRun(),','() => void approveAndRun(),\n pendingPlan.kind === "dynamic"&&(!uploadConfirmed||!runtimeConfirmed),',1).replace('text-[11px]','text-sm')
for required in ['AnalysisAuthoring','advanced_options:JSON.parse','confirmArtifactUpload:uploadConfirmed','worker endpoint','cfg_analyze']:
 if required not in v:raise RuntimeError('Workbench integration anchor missing: '+required)
put(path,v)
path='apps/examples/desktop-app/package.json';v=base(path).replace('vitest run webview/components/views/chat/analysis-workbench.test.tsx','vitest run webview/components/views/chat/analysis-authoring.test.tsx webview/components/views/chat/analysis-workbench.test.tsx');put(path,v)
put('apps/examples/desktop-app/webview/components/views/chat/analysis-authoring.test.tsx','''// @vitest-environment jsdom
import {act} from "react";import {createRoot} from "react-dom/client";import {it,expect,vi} from "vitest";import {desktopClient} from "@/lib/desktop-client";import {AnalysisAuthoring} from "./analysis-authoring";
it.each(["notebook","graph"] as const)("separates %s file write from analysis approval",async kind=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});const box=document.createElement("div");document.body.appendChild(box);const root=createRoot(box),prepare=vi.fn(async()=>{}),invoke=vi.spyOn(desktopClient,"invoke").mockResolvedValue({path:"/workspace/owned.json",sha256:"a".repeat(64)});try{await act(async()=>root.render(<AnalysisAuthoring kind={kind} common={{cwd:"/workspace"}} onPrepare={prepare}/>));const save=()=>[...box.querySelectorAll("button")].find(b=>b.textContent?.includes("Validate and save"))!;expect(save().disabled).toBe(true);await act(async()=>box.querySelector<HTMLInputElement>('input[type="checkbox"]')!.click());await act(async()=>{save().click();await Promise.resolve();});expect(invoke).toHaveBeenCalledWith("save_analysis_document",expect.objectContaining({confirmWrite:true,kind}));expect(prepare).not.toHaveBeenCalled();const button=[...box.querySelectorAll("button")].find(b=>b.textContent?.includes(kind==="notebook"?"Prepare notebook preflight":"Prepare graph query"))!;await act(async()=>{button.click();await Promise.resolve();});expect(prepare).toHaveBeenCalledWith(expect.objectContaining({advanced_action:kind==="notebook"?"notebook_validate":"graph_query",target:"/workspace/owned.json"}));}finally{await act(async()=>root.unmount());box.remove();vi.restoreAllMocks();}});
''')
path='apps/examples/desktop-app/sidecar/analysis-document-store.ts';v=base(path).replace('else if(input.kind === "graph")EvidenceGraphSchema.parse(parsed);','else if(input.kind === "graph"){const graph=EvidenceGraphSchema.parse(parsed),ids=new Set(graph.nodes.map(n=>n.id));if(ids.size!==graph.nodes.length||graph.nodes.some(n=>!n.id)||graph.edges.some(e=>!ids.has(e.source)||!ids.has(e.target)))throw new Error("Graph requires unique nodes and valid edge endpoints");}');put(path,v)
path='apps/examples/desktop-app/sidecar/analysis-sandbox-client.ts';v=base(path).replace('typeof manifest.workerId === "string" &&','typeof manifest.workerId === "string" && manifest.workerId.length>0 && manifest.workerId.length<=128 &&').replace('typeof manifest.version === "string" &&','typeof manifest.version === "string" && manifest.version.length>0 && manifest.version.length<=128 &&').replace('Number.isFinite(manifest.maxArtifactBytes)','Number.isSafeInteger(manifest.maxArtifactBytes)').replace('!new URL(endpoint).hash,','!new URL(endpoint).hash && !new URL(endpoint).search && new URL(endpoint).pathname === "/",').replace('const health=await probeAnalysisSandbox(fetchImpl),cfg=configuration();if(!health.ready||!health.manifest||!cfg.publicKey','const health=await probeAnalysisSandbox(fetchImpl),cfg=configuration();if(signal?.aborted)throw new Error("Cancelled before submission");if(!health.ready||!health.manifest||!cfg.publicKey',1).replace('createPublicKey(config.publicKey)','workerPublicKey(config.publicKey)').replace('createPublicKey(cfg.publicKey)','workerPublicKey(cfg.publicKey)').replace('createPublicKey(key).export','workerPublicKey(key).export');v+='\nfunction workerPublicKey(pem:string){const key=createPublicKey(pem);if(key.asymmetricKeyType!=="ed25519")throw new Error("Worker requires an Ed25519 key");return key;}\n';put(path,v)
path='.github/workflows/build-custom-windows-installer.yml';v=base(path);a=v.index('      - name: Upload consolidated validation evidence');v=v[:a]+'''      - name: Validate portable Windows analysis engines
        shell: pwsh
        run: |
          $engineRoot = Join-Path $env:RUNNER_TEMP 'cline-portable-engines'
          py -3.13 -m venv $engineRoot
          if ($LASTEXITCODE -ne 0) { throw "Python 3.13 environment creation failed" }
          $python = Join-Path $engineRoot 'Scripts/python.exe'
          & $python -m pip install --disable-pip-version-check -r sdk/packages/core/scripts/requirements-advanced-windows.txt
          if ($LASTEXITCODE -ne 0) { throw "Pinned portable engine installation failed" }
          $env:CLINE_RE_PYTHON = $python
          Push-Location sdk
          try { bun test packages/core/scripts/advanced-windows-engine-smoke.test.ts; if ($LASTEXITCODE -ne 0) { throw "Real portable engine execution failed" } }
          finally { Pop-Location }

'''+v[a:];put(path,v)
path='CUSTOMIZATIONS.md';put(path,base(path)+'''\n- V4 document authoring uses separate save/run approval, a 1 MiB limit and hash-guarded updates. Runtime submission has independent upload/execution acknowledgments, exact worker/artifact binding, strict Ed25519 keys and bounded signed receipts.\n- Installer packaging requires six real portable-engine SDK-to-worker tests, not merely package presence. Python and these dependencies are CI-only and not bundled in the installer. No live QBDI backend, licensed adapter, full unflattening or VM provisioning is claimed.\n''')
path='scripts/verify-custom-fork.ts';v=base(path);a=v.index('const forbiddenPaths');v=v[:a]+'''requiredMarkers.push({path:"apps/examples/desktop-app/webview/components/views/chat/analysis-authoring.tsx",markers:["expectedSha256","Saving never executes analysis","graph_query"]},{path:".github/workflows/build-custom-windows-installer.yml",markers:["Validate portable Windows analysis engines","advanced-windows-engine-smoke.test.ts","Real portable engine execution failed"]});
'''+v[a:];put(path,v)
put('docs/V4_IMPLEMENTATION_STATUS.md','''# V4 capability status\n\nImplemented source: imported CFG dominance/loops/SCCs; explicit-location trace slices and overwrite-aware influence; data-only notebook/graph authoring; immutable worker/artifact-bound approval and signed submission receipts; bridge hardening; mandatory portable Windows engine execution.\n\nSource tests and source recovery are not installer proof. Verify the dedicated-branch GitHub Actions installer run, installed-app/sidecar smoke and verified artifact before treating packaging as successful. CI commits materialized source before starting the installer workflow.\n\nThe six-engine corpus executes LIEF ELF parsing, Capstone disassembly, Z3 expression equivalence, Miasm bounded IR, Androguard DEX indexing and authenticated AES-GCM decryption/failure. Missing engines fail. These dependencies are CI-only, not bundled into the installer, and do not validate Triton/QBinDiff, QBDI or licensed tools.\n\nNot implemented: real QBDI worker/deployment, FlowDroid lifecycle analysis, Remill, JEB/IDA-D810, full unflattening/devirtualization, key recovery and automatic/measured VM provisioning. Imported dependencies are not opcode-semantic taint or actual trace acquisition. Signed capabilities are operator claims, not hardware attestation; local cancellation does not prove remote teardown. Full recommendations remain unfinished. No automatic merge, tag or release.\n''')
marker.write_text(json.dumps({'generatorSha256':identity,'base':BASE,'files':changed,'hashes':{p:hashlib.sha256((r/p).read_bytes()).hexdigest() for p in changed}},indent=2)+'\n')
print('Materialized',len(changed),'source files. Commit them before installer dispatch.')
